<?php

/* Author: Giorgos Strimpakos */

$labels = array();
$labels['too_many_files_to_upload'] = 'Μπορείτε να ανεβάσετε μέχρι και 4 αρχεία την φορά.';
$labels['files_to_upload_bigger_than_allowed'] = 'Το μέγεθος των αρχείων που θέλετε να μεταφορτώσετε, ξεπερνάει το επιτρεπόμενο όριο των 10Mb';

$messages = array();
$messages['all_files_successfully_uploaded'] = 'Τα αρχεία μεταφορτώθηκαν με επιτυχία';
